# Site settings
title: "TripleA: The World's Foremost Open Source Grand Strategy Game"
description: TripleA is a free online turn based strategy game and board game engine, similar to such board games as Axis &amp; Allies or Risk. TripleA comes with multiple games and over 100 more maps can be downloaded from the user community. Supports single player vs AI, hot-seat, play by email and forum, and a hosted Online lobby for live play online.
markdown: kramdown

game-version: 1.9.0.0.3446
# size of the win64 download, won't be exact for each downloader, but will give a good benchmark 
dl-size-mb: 49
