# Site settings
title: "TripleA: An Open Source Turn Based Grand Strategy Game"
description: TripleA is a free open source turn based grand strategy game engine with play similar to Axis & Allies and Risk. Over a hundred different maps created by the community covering a wide variety of scenarios (such as WW1, WW2 and various science fiction and fantasy worlds) are available for download. TripleA supports single player vs AI, hot-seat, play by email and forum, direct online play, and a hosted lobby for live online play with other community members.
markdown: kramdown
sass:
  style: compressed

collections:
  maps:
    output: true
    permalink: /map/:path/

defaults:
  - scope:
      path: ""
      type: maps
    values:
      layout: map

exclude:
  - README.md
  - CNAME
